# Generated by Django 5.0.2 on 2024-02-20 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_subchat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subchat',
            old_name='chat',
            new_name='room',
        ),
    ]
